# The image source is available at https://github.com/amredev/imaginarium
FROM ghcr.io/amredev/devcontainer-decondenser:0.3.0

RUN ln -s "$CONTAINER_WORKSPACE/.devcontainer/init.sh" "$HOME/devcontainer-hooks/init.sh"
