package amredev:decondenser;

world decondenser {
    export decondenser: interface {
        unescape: func(params: unescape-params) -> unescape-output;
        record unescape-params {
            input: string,
        }
        record unescape-output {
            output: string,
        }

        format: func(params: format-params) -> format-output;
        record format-params {
            input: string,
        }
        record format-output {
            output: string,
        }
    }
}
